# Minimal example: the component publishes *sensor resistances* (Rs in Ohm).
# These three sensors are REQUIRED by the current component schema.
esphome:
  name: mics6814_demo

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

external_components:
  - source:
      type: local
      path: ./components
    components: [ pimoroni_mics6814 ]

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: pimoroni_mics6814
    id: mics0
    # IO Expander address is commonly 0x18 or 0x19. Use i2c.scan to confirm.
    address: 0x19
    update_interval: 10s

    oxidising:
      name: "MICS Oxidising Rs (Ohm)"
    reducing:
      name: "MICS Reducing Rs (Ohm)"
    nh3:
      name: "MICS NH3 Rs (Ohm)"
