# Advanced example: same as full, but with DEBUG logging.
esphome:
  name: mics6814_advanced

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

external_components:
  - source:
      type: local
      path: ./components
    components: [ pimoroni_mics6814 ]

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: pimoroni_mics6814
    id: mics0
    address: 0x19
    update_interval: 10s
    oxidising:
      name: "MICS Oxidising Rs (Ohm)"
    reducing:
      name: "MICS Reducing Rs (Ohm)"
    nh3:
      name: "MICS NH3 Rs (Ohm)"
    ref_voltage:
      name: "MICS Ref Voltage (V)"
    r0_oxidising:
      name: "MICS Oxidising R0 (Ohm)"
    r0_reducing:
      name: "MICS Reducing R0 (Ohm)"
    r0_nh3:
      name: "MICS NH3 R0 (Ohm)"
    ratio_oxidising:
      name: "MICS Oxidising Rs/R0"
    ratio_reducing:
      name: "MICS Reducing Rs/R0"
    ratio_nh3:
      name: "MICS NH3 Rs/R0"

switch:
  - platform: pimoroni_mics6814
    name: "MICS Heater"
    mics_id: mics0

button:
  - platform: pimoroni_mics6814
    name: "MICS Calibrate R0 (mean)"
    mics_id: mics0

