# Advanced: manual R0 set + calibration window tuning.
esphome:
  name: mics6814_advanced

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:

external_components:
  - source:
      type: local
      path: ./components
    components: [ pimoroni_mics6814 ]

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

sensor:
  - platform: pimoroni_mics6814
    id: mics0
    address: 0x19
    update_interval: 10s
    calibration_window_seconds: 30
    oxidising:
      name: "MICS Oxidising ADC (raw)"
    reducing:
      name: "MICS Reducing ADC (raw)"
    nh3:
      name: "MICS NH3 ADC (raw)"
    oxidising_resistance:
      name: "MICS Oxidising Rs (Ohm)"
    reducing_resistance:
      name: "MICS Reducing Rs (Ohm)"
    nh3_resistance:
      name: "MICS NH3 Rs (Ohm)"
    oxidising_r0:
      name: "MICS Oxidising R0 (Ohm)"
    reducing_r0:
      name: "MICS Reducing R0 (Ohm)"
    nh3_r0:
      name: "MICS NH3 R0 (Ohm)"
    oxidising_ratio:
      name: "MICS Oxidising Rs/R0"
    reducing_ratio:
      name: "MICS Reducing Rs/R0"
    nh3_ratio:
      name: "MICS NH3 Rs/R0"

number:
  - platform: pimoroni_mics6814
    name: "Set Oxidising R0 (Ohm)"
    mics_id: mics0
    channel: oxidising
    min_value: 100
    max_value: 1000000
    step: 10

  - platform: pimoroni_mics6814
    name: "Set Reducing R0 (Ohm)"
    mics_id: mics0
    channel: reducing
    min_value: 100
    max_value: 1000000
    step: 10

  - platform: pimoroni_mics6814
    name: "Set NH3 R0 (Ohm)"
    mics_id: mics0
    channel: nh3
    min_value: 100
    max_value: 1000000
    step: 10

switch:
  - platform: pimoroni_mics6814
    name: "MICS Heater"
    mics_id: mics0

button:
  - platform: pimoroni_mics6814
    name: "Calibrate R0 (mean)"
    mics_id: mics0
